# Generated by Django 2.1.1 on 2019-08-23 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=15)),
                ('email', models.CharField(default='', max_length=15)),
                ('subject', models.CharField(default='', max_length=15)),
                ('message', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=100000)),
                ('option1', models.CharField(default='', max_length=10000)),
                ('option2', models.CharField(default='', max_length=10000)),
                ('option3', models.CharField(default='', max_length=10000)),
                ('correct', models.CharField(default='', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organiser', models.CharField(default='', max_length=200)),
                ('name_quiz', models.CharField(max_length=200, unique=True)),
                ('number_quiz', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Test_Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('score_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=15)),
                ('score', models.IntegerField(default=0)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.Quiz'),
        ),
    ]
