# Generated by Django 2.1.1 on 2019-08-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
