# Generated by Django 2.1.1 on 2019-08-22 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Quiz', '0002_feedback_user_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1', models.CharField(default='', max_length=10000)),
                ('option2', models.CharField(default='', max_length=10000)),
                ('option3', models.CharField(default='', max_length=10000)),
                ('correct', models.CharField(default='', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Test_Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('score_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.Quiz')),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='num_questions',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_delete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.Questions'),
        ),
    ]
