# Generated by Django 2.1.1 on 2019-08-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_auto_20190822_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='num_questions',
        ),
        migrations.AddField(
            model_name='quiz',
            name='number_quiz',
            field=models.IntegerField(default=0),
        ),
    ]
