# Generated by Django 2.1.1 on 2019-08-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_auto_20190822_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='relation',
        ),
        migrations.AddField(
            model_name='questions',
            name='correct',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='questions',
            name='option1',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='questions',
            name='option2',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='questions',
            name='option3',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
