# Generated by Django 2.1.1 on 2019-08-25 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_auto_20190825_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='correct',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='number_quiz',
        ),
        migrations.RemoveField(
            model_name='test_score',
            name='score',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='score',
        ),
    ]
