# Generated by Django 2.1.1 on 2019-08-23 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_user_info_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_score',
            name='attempted',
        ),
    ]
