# Generated by Django 2.1.1 on 2019-08-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_test_score_attempted'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='option1_per',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='option2_per',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='option3_per',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='attempt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
