# Generated by Django 2.1.1 on 2019-08-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_auto_20190825_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='option1_percentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='option2_percentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='option3_percentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
